### PR TITLE
Changes made for table iteration

### PR DESCRIPTION
**Pull request by rabelmervin**
**Description**

Initially the tables used a simple string method of matching. Now its updated to iteration method that iterates over the tables.

### CODE REVIEW

**Comment by tedivm** [comment]
Can you fix the formatting so that test passes, and add some new tests (leaving the existing ones as is) to show the new functionality?

**Comment by rabelmervin** [comment]
Sure @tedivm 👍

**Comment by tedivm** [comment]
Should we close this PR in favor of #26 ?

**Comment by rabelmervin** [comment]
Yeah @tedivm  we can close it

**Pull request closed without merging**
